# -*- coding: utf-8 -*-
"""denguefinal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nWlexVh-TRPmuhOXsUkfGm0p-XR8hmum

**IMPORTING THE LIBRARIES**
"""

import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt
import seaborn as sns

dengue_dataset = pd.read_csv('/content/Dengue_Dataset_1.csv')



"""**Showing Rows, Columns and Shape of Dataset:**"""

dengue_dataset.head()

dengue_dataset

dengue_dataset.tail()

print(dengue_dataset.columns)

dengue_dataset.shape

"""**Shows Number of Null Values present among attributes/columns of the Initial Dataset:**"""

dengue_dataset.isnull().sum()

missing_values = dengue_dataset.isnull()

missing_counts = missing_values.sum()

print("Columns with missing values:")
print(missing_counts[missing_counts > 0])

"""**Visualization of all missing values with a Heatmap**"""

sns.heatmap(missing_values, cbar=False, cmap='viridis', linecolor = 'white')
plt.show()

"""**Visualization of missing values of LLBplatelet**"""

sns.distplot(dengue_dataset['LLBplatelet'])

"""**Visualization of missing values of Bleeding**"""

sns.distplot(dengue_dataset['Bleeding '])

"""**Visualization of missing values of Vomiting**"""

sns.distplot(dengue_dataset['Vomiting '])

"""**HANDLING MISSING VALUES**"""

# Check for missing values
missing_values = dengue_dataset.isnull()

# Count missing values for each column
missing_counts = missing_values.sum()

dengue_dataset.fillna(dengue_dataset.mean(), inplace=True)

# Display columns with missing values and their counts
print("Columns with missing values:")
print(missing_counts[missing_counts > 0])

dengue_dataset.isnull().sum()

sns.heatmap(missing_values, cbar=False, cmap='viridis', linecolor = 'white')
plt.show()

"""**SPLITTING THE DATA INTO TRAINING DATA & TESTING DATA**"""

X = dengue_dataset.drop(columns = 'NS1', axis=1)
Y = dengue_dataset['NS1']

print(X)

print(Y)

dengue_dataset['NS1'].value_counts()

"""**1 --> Dengue Positive;  0 --> Dengue Negative**"""

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=3)

print(X.shape, X_train.shape, X_test.shape)

print(Y.shape, Y_train.shape, Y_test.shape)

"""**DATA VISUALIZATION**

**Distribution of results**
"""

# Count the occurrences of each result
result_counts = dengue_dataset['NS1'].value_counts()

# Plot the bar chart
plt.bar(result_counts.index, result_counts.values, color=['green', 'red'])
plt.xlabel('NS1')
plt.ylabel('Count')
plt.title('Distribution of Results')
plt.show()

"""**Heatmap**"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt



attributes = ['Age', ' Sex', 'Work', 'BpSys', 'Bpdias', 'Pulse', 'Cough', 'Fever',
       'LLBplatelet', 'Headache', 'Muscle pain', 'Bleeding ', 'Skinrash',
       'Vomiting ', 'Diarrhoea ', 'IgG', 'IgM', 'Fatigue', 'Rapid breathing ',
       'NS1']

# Select the 21 attributes from the dataset
selected_data = dengue_dataset[attributes]

# Calculate the correlation matrix
correlation_matrix = selected_data.corr()

# Create a heatmap
plt.figure(figsize=(14, 10))
heatmap = sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', linewidths=.5)
plt.title('Correlation Heatmap of Dengue Detection Attributes')
plt.show()

"""**Count plot for Categorical binary value**"""



# Python Code:
# Assuming 'categorical_binary' is a list of categorical features with binary values
categorical_binary = [' Sex','Cough','LLBplatelet','Headache','Bleeding ','IgG', 'IgM', 'Fatigue','Rapid breathing ','NS1']

# Plot the count plots for each feature
for feature in categorical_binary:
    plt.figure(figsize=(8, 6))
    sns.countplot(x=feature, data=dengue_dataset)
    plt.title(f'Count Plot for {feature}')
    plt.show()

"""**Box plot for categorical non binary value**"""

categorical_non_binary = ['Age','Work', 'BpSys', 'Bpdias','Pulse','Fever','Muscle pain','Skinrash','Vomiting ','Diarrhoea ']

for feature in categorical_non_binary:
    plt.figure(figsize=(8, 6))
    sns.boxplot(x=dengue_dataset[feature])  # Change 'column' to 'feature'
    plt.title(f"Box Plot - {feature}")
    plt.show()

"""**Histograms for All Parameters:**"""

dengue_dataset.hist(figsize=(15, 12), bins=10,edgecolor='black')
plt.suptitle("Histograms for All Parameters", y=1.02)
plt.show()

import numpy as np
import pandas as pd

from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

import sklearn
from sklearn import svm

print(sklearn.__version__)

# Create instances of each model and insert them into a list
models = [
    svm.SVC(kernel='linear'),  # Specify linear kernel here
   #feature extraction of DT
    DecisionTreeClassifier(),
    XGBClassifier(),
    GaussianNB(),
    RandomForestClassifier(),
    KNeighborsClassifier(),
    LogisticRegression(),
    LinearDiscriminantAnalysis()
]

dengue_dataset.isnull().sum()

from sklearn.model_selection import train_test_split

X = dengue_dataset.drop('NS1', axis=1)
y = dengue_dataset['NS1']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

for model in models:
  model.fit(X_train, y_train)


  y_train_pred = model.predict(X_train)
  y_test_pred = model.predict(X_test)

  train_accuracy = accuracy_score(y_train, y_train_pred)
  train_precision = precision_score(y_train, y_train_pred)
  train_recall = recall_score(y_train, y_train_pred)
  train_f1 = f1_score(y_train, y_train_pred)

  test_accuracy = accuracy_score(y_test, y_test_pred)
  test_precision = precision_score(y_test, y_test_pred)
  test_recall = recall_score(y_test, y_test_pred)
  test_f1 = f1_score(y_test, y_test_pred)

  print(f"-------------------Training Metrics for {model}----------------")
  print(f"Train Accuracy: {train_accuracy:.4f}")
  print(f"Precision: {train_precision:.4f}")
  print(f"Recall: {train_recall:.4f}")
  print(f"F1 Score: {train_f1:.4f}")
  print("\n-------------------Test Metrics-------------------")
  print(f"Test Accuracy: {test_accuracy:.4f}")
  print(f"Precision: {test_precision:.4f}")
  print(f"Recall: {test_recall:.4f}")
  print(f"F1 Score: {test_f1:.4f}")

import matplotlib.pyplot as plt

classifiers = ['Kneighbors', 'LogisticRegression', 'Linear Discriminant Analysis', 'GaussianNB', 'Svc', 'XGBClassifier',  'Decision tree',  'RandomForest']
accuracies = [0.9907, 1.00, 0.9953, 0.9907, 1.00, 0.8465, 0.9907, 0.9907]
colors = ['blue', 'green', 'orange', 'red', 'purple', 'brown', 'pink', 'gray']

plt.figure(figsize=(10, 6))
plt.bar(classifiers, accuracies, color=colors)
plt.xlabel('Classifiers')
plt.ylabel('Accuracy')
plt.title('Train Accuracy Comparison of Different Classifiers')
plt.ylim(0.8, 1.0)
plt.xticks(rotation=45, ha='right')
plt.show()

import matplotlib.pyplot as plt

classifiers = ['SVC', 'Decision Tree', 'XGBClassifier', 'GaussianNB', 'RandomForest', 'KNeighbors', 'Logistic Regression', 'Linear Discriminant Analysis']
accuracies = [0.9677, 0.9677, 0.9892, 0.9892, 0.9892, 0.8280, 0.9570, 0.9785]
colors = ['blue', 'orange', 'green', 'red', 'purple', 'brown', 'pink', 'gray']

plt.figure(figsize=(10, 6))
bars = plt.bar(classifiers, accuracies, color=colors)
plt.xlabel('Classifiers')
plt.ylabel('Test Accuracy')
plt.title('Test Accuracy Comparison of Different Classifiers')
plt.ylim(0.8, 1.0)
plt.xticks(rotation=45, ha='right')
plt.show()

import matplotlib.pyplot as plt

classifiers = ['Svc', 'Decision tree', 'XGBClassifier', 'GaussianNB', 'RandomForest', 'Kneighbors', 'LogisticRegression', 'Linear Discriminant Analysis']
f1_scores = [0.9748, 0.9748, 0.9917, 0.9917, 0.9917, 0.8730, 0.9661, 0.9833]
colors = ['blue', 'orange', 'green', 'red', 'purple', 'brown', 'pink', 'gray']

plt.figure(figsize=(10, 6))
plt.bar(classifiers, f1_scores, color=colors)
plt.xlabel('Classifiers')
plt.ylabel('F1 Score')
plt.title('F1 Score Comparison of Different Classifiers')
plt.ylim(0.8, 1.0)
plt.xticks(rotation=45, ha='right')
plt.show()



from sklearn.metrics import confusion_matrix
import seaborn as sns

# Function to plot confusion matrix
def plot_confusion_matrix(y_true, y_pred, title):
    cm = confusion_matrix(y_true, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, cmap='Blues', fmt='d', cbar=False)
    plt.xlabel('Predicted')
    plt.ylabel('Actual')
    plt.title(title)
    plt.show()

# Calculate confusion matrices and plot for each model
for model in models:
    # Fit the model
    model.fit(X_train, y_train)

    # Making predictions on the train and test sets
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Plot confusion matrix for train set
    plot_confusion_matrix(y_train, y_train_pred, f'Confusion Matrix for {model.__class__.__name__} (Train)')

    # Plot confusion matrix for test set
    plot_confusion_matrix(y_test, y_test_pred, f'Confusion Matrix for {model.__class__.__name__} (Test)')

import pickle

filename = 'trained_model_main.sav'
pickle.dump(models, open(filename, 'wb'))

loaded_model = pickle.load(open('trained_model_main.sav', 'rb'))

import matplotlib.pyplot as plt
from sklearn.metrics import roc_curve, auc
models = [
    svm.SVC(kernel='linear', probability=True),
    DecisionTreeClassifier(),
    XGBClassifier(),
    GaussianNB(),
    RandomForestClassifier(),
    KNeighborsClassifier(),
    LogisticRegression(),
    LinearDiscriminantAnalysis()
]


probas = [model.fit(X_train, y_train).predict_proba(X_test)[:, 1] for model in models]
p

plt.figure(figsize=(10, 8))
for i, model in enumerate(models):
    fpr, tpr, _ = roc_curve(y_test, probas[i])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, label=f'{model.__class__.__name__} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], linestyle='--', color='r', label='Random')
plt.xlim([0.0, 1.0])
plt.ylim([0.0, 1.05])
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic (ROC) Curve')
plt.legend(loc="lower right")
plt.show()

from sklearn.metrics import roc_auc_score

auc_scores = {}
for model in models:
    model.fit(X_train, y_train)
    y_pred_prob = model.predict_proba(X_test)[:, 1]
    roc_auc = roc_auc_score(y_test, y_pred_prob)
    auc_scores[model.__class__.__name__] = roc_auc

# Print AUC scores
for model_name, auc_score in auc_scores.items():
    print(f"{model_name}: AUC = {auc_score:.2f}")

import numpy as np
from sklearn.model_selection import learning_curve

# Define different training set sizes (you can adjust this as needed)
train_sizes = np.linspace(0.1, 1.0, 10)

# Initialize lists to store training and test AUC scores for each model
train_auc_scores = []
test_auc_scores = []

# Calculate AUC scores for different training set sizes
for model in models:
    train_sizes, train_auc, test_auc = learning_curve(model, X, y, cv=5, train_sizes=train_sizes, scoring='roc_auc')
    train_auc_scores.append(np.mean(train_auc, axis=1))
    test_auc_scores.append(np.mean(test_auc, axis=1))

# Plot AUC curve
plt.figure(figsize=(10, 6))
for i, model_name in enumerate([model.__class__.__name__ for model in models]):
    plt.plot(train_sizes, train_auc_scores[i], label=f'{model_name} (Train)', linestyle='--')
    plt.plot(train_sizes, test_auc_scores[i], label=f'{model_name} (Test)')

plt.title('AUC Curve')
plt.xlabel('Training Examples')
plt.ylabel('AUC Score')
plt.legend()
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

# Assuming 'models' has trained models and X_test, y_test are test data

# Create an empty confusion matrix
confusion_matrices = []
for model in models:
  y_pred = model.predict(X_test)
  confusion_matrix_values = confusion_matrix(y_test, y_pred)
  confusion_matrices.append(confusion_matrix_values)

# Plot the confusion matrices for each model
for i, model_name in enumerate([model.__class__.__name__ for model in models]):
  plt.figure(figsize=(6, 6))
  plt.imshow(confusion_matrices[i], cmap='Blues')
  plt.colorbar()
  plt.title(f'Confusion Matrix for {model_name}')
  plt.xlabel('Predicted Label')
  plt.ylabel('True Label')
  plt.xticks([0, 1], ['Negative', 'Positive'])
  plt.yticks([0, 1], ['Negative', 'Positive'])
  plt.show()

import pandas as pd

# Initialize lists to store evaluation metrics for each model
model_names = []
train_accuracy_list = []
train_precision_list = []
train_recall_list = []
train_f1_list = []
test_accuracy_list = []
test_precision_list = []
test_recall_list = []
test_f1_list = []

# Calculate evaluation metrics for each model
for model in models:
    model_names.append(model.__class__.__name__)

    # Fit the model
    model.fit(X_train, y_train)

    # Making predictions on the train and test sets
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Calculate metrics on the training set
    train_accuracy = accuracy_score(y_train, y_train_pred)
    train_precision = precision_score(y_train, y_train_pred)
    train_recall = recall_score(y_train, y_train_pred)
    train_f1 = f1_score(y_train, y_train_pred)

    # Calculate metrics on the test set
    test_accuracy = accuracy_score(y_test, y_test_pred)
    test_precision = precision_score(y_test, y_test_pred)
    test_recall = recall_score(y_test, y_test_pred)
    test_f1 = f1_score(y_test, y_test_pred)

    # Append metrics to the respective lists
    train_accuracy_list.append(train_accuracy)
    train_precision_list.append(train_precision)
    train_recall_list.append(train_recall)
    train_f1_list.append(train_f1)
    test_accuracy_list.append(test_accuracy)
    test_precision_list.append(test_precision)
    test_recall_list.append(test_recall)
    test_f1_list.append(test_f1)

# Create a DataFrame to store the evaluation metrics
metrics_df = pd.DataFrame({
    'Model': model_names,
    'Train Accuracy': train_accuracy_list,
    'Train Precision': train_precision_list,
    'Train Recall': train_recall_list,
    'Train F1 Score': train_f1_list,
    'Test Accuracy': test_accuracy_list,
    'Test Precision': test_precision_list,
    'Test Recall': test_recall_list,
    'Test F1 Score': test_f1_list
})

# Display the DataFrame
print(metrics_df)

import seaborn as sns
import matplotlib.pyplot as plt

# Create a DataFrame to store the evaluation metrics
metrics_df = pd.DataFrame({
    'Model': model_names,
    'Train Accuracy': train_accuracy_list,
    'Train Precision': train_precision_list,
    'Train Recall': train_recall_list,
    'Train F1 Score': train_f1_list,
    'Test Accuracy': test_accuracy_list,
    'Test Precision': test_precision_list,
    'Test Recall': test_recall_list,
    'Test F1 Score': test_f1_list
})

# Set the 'Model' column as the index
metrics_df.set_index('Model', inplace=True)

# Plot the heatmap
plt.figure(figsize=(12, 8))
sns.heatmap(metrics_df, annot=True, cmap='coolwarm', fmt=".3f", linewidths=.5)
plt.title('Evaluation Metrics for Different Models')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Data
models = ['SVC', 'DecisionTree', 'XGB', 'GaussianNB', 'RandomForest', 'KNeighbors', 'LogisticRegression', 'LinearDiscriminant']
train_accuracy = [0.9907, 1.0000, 0.9953, 0.9907, 1.0000, 0.8465, 0.9907, 0.9907]
test_accuracy = [0.9677, 0.9677, 0.9892, 0.9892, 0.9892, 0.8280, 0.9570, 0.9785]
f1_score = [0.9748, 0.9748, 0.9917, 0.9917, 0.9917, 0.8730, 0.9661, 0.9833]

# Set width of bar
barWidth = 0.25

# Set position of bar on X axis
r1 = np.arange(len(train_accuracy))
r2 = [x + barWidth for x in r1]
r3 = [x + barWidth for x in r2]

# Make the plot
plt.figure(figsize=(12, 6))
plt.bar(r1, train_accuracy, color='blue', width=barWidth, edgecolor='grey', label='Train Accuracy')
plt.bar(r2, test_accuracy, color='red', width=barWidth, edgecolor='grey', label='Test Accuracy')
plt.bar(r3, f1_score, color='green', width=barWidth, edgecolor='grey', label='F1 Score')

# Add xticks on the middle of the group bars
plt.xlabel('Models', fontweight='bold')
plt.xticks([r + barWidth for r in range(len(train_accuracy))], models, rotation=45)

# Add ylabel
plt.ylabel('Scores', fontweight='bold')

# Add legend
plt.legend()

# Show plot
plt.show()

import pandas as pd

# Data
data = {
    'Model': models,
    'Train Accuracy': train_accuracy,
    'Test Accuracy': test_accuracy,
    'F1 Score': f1_score
}

# Create DataFrame
df = pd.DataFrame(data)

# Display the DataFrame
print(df.to_string(index=False))